### ISSUE TITLE
Первая итерация ревью

### ISSUE THREAD

**Issue by akhtyamovpavel** [joein/telegram_marvel_bot#1]
Привет!

Проект по оформлению отличный! Из плюсов - читаемый код! 
* https://github.com/joein/telegram_marvel_bot/blob/master/config.py#L8 - отличная история с хранением секретов
* Детальный readme с описанием функций
Смотрю первую итерацию ревью - вот некоторые моменты:

- [x] https://github.com/joein/telegram_marvel_bot/blob/master/Dockerfile#L6 - лучше использовать &&, а не ; Поскольку в этом случае мы не будем двигаться дальше, если команда не будет выполнена успешно
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/bot.py#L21 - что такое `conv`? Лучше либо использовать полное название, либо не использовать его вовсе (особенно, если это название содержит тип)
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/bot.py#L16 - а почему `fetcher_`?
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/conv_handler_builder.py#L60 - что такое `characters`? Функция - это действие, а действие выражается глаголом или глагольной фразой - возможно, лучше сделать так: `get_characters`
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/conv_handler_builder.py#L83 - думаю, что стоит подумать над сокращением названий переменных (предлоги можно опускать, `map` - это как раз история с типами, которую я уже выше описал)
- [ ] https://github.com/joein/telegram_marvel_bot/blob/master/conv_handler_builder.py#L92 - я придираюсь, но лучше сделать форматирование, как ниже
- [x] Посмотри по файлу `conv_handler_builder` - замечания выше относятся не только к описанным мною случаям, но и аналогичным
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/fetcher.py#L42 - а почему здесь оформление не через словарь обычный, а через `dict`?
- [ ] https://github.com/joein/telegram_marvel_bot/blob/master/fetcher.py#L37 - слишком много аргументов передается в функцию, это можно поправить?
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/fetcher.py#L68-L71 - думаю, что можно вынести в отдельный файл эту информацию, после чего использовать функцию `format`
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/entities.py#L96-L109 - очень много аргументов. Для решения этой проблемы можно использовать паттерн проектирования Builder
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/entities.py - давай сделаем отдельный package, в каждом файле которого будет один из персонажей - так проще будет и мне код смотреть, и тебе его поддерживать
- [x] https://github.com/joein/telegram_marvel_bot/blob/master/marvel_handlers.py - аналогично с handler-ами

Буду ждать новой итерации!

**Comment by joein** [comment]
@akhtyamovpavel 

>  https://github.com/joein/telegram_marvel_bot/blob/master/bot.py#L21 - что такое conv? Лучше либо использовать полное название, либо не использовать его вовсе (особенно, если это название содержит тип)

Сокращение от conversation

> https://github.com/joein/telegram_marvel_bot/blob/master/conv_handler_builder.py#L92 - я придираюсь, но лучше сделать форматирование, как ниже

Я использую авто-форматирование black и по умолчанию он применяет такое форматирование, не планирую это менять

> https://github.com/joein/telegram_marvel_bot/blob/master/bot.py#L16 - а почему fetcher_? 

Это было сделано для того, чтобы не перезатирать существующий объект из глобальной области видимости, поменял их местами

> https://github.com/joein/telegram_marvel_bot/blob/master/fetcher.py#L42 - а почему здесь оформление не через словарь обычный, а через dict? 

Не несет какого-то сакрального смысла, заменил на обычные {}

> https://github.com/joein/telegram_marvel_bot/blob/master/fetcher.py#L37 - слишком много аргументов передается в функцию, это можно поправить?

Этот метод задумывался именно как staticmethod, он получает все необходимые ему для работы аргументы, можно как-то скомпоновать принимаемые аргументы, но особого смысла не вижу.

>  https://github.com/joein/telegram_marvel_bot/blob/master/fetcher.py#L68-L71 - думаю, что можно вынести в отдельный файл эту информацию, после чего использовать функцию format

На данном этапе не хочу создавать отдельный файл для хранения такого типа строк, создал кастомный exception и поместил это туда
